export const ADD_NEW_TASKS_ARRAY = 'TASKS/ADD-NEW-TASKS-ARRAY'
export const ADD_TASK = 'TASKS/ADD-TASK'

export const REMOVE_TASK = 'TASKS/REMOVE-TASK'
export const REMOVE_TASKS_ARRAY = 'TASKS/REMOVE-TASKS-ARRAY'

export const CHANGE_TASK_TITLE = 'TASKS/CHANGE-TASK-TITLE'
export const CHANGE_SELECT = 'TASKS/CHANGE-SELECT'

export const SET_NEW_TASK_TITLE = 'TASKS/SET-NEW-TASK-TITLE'